# Generated by Django 5.1.5 on 2025-02-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_usuario_comprobante_pago_usuario_is_tec_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ronda',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='ronda',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='descripcion_resultado',
        ),
        migrations.AddField(
            model_name='ronda',
            name='lugar',
            field=models.CharField(default='https://maps.app.goo.gl/FsC7JDNnky76Le7e6', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_ganados', to='Registro.robot'),
        ),
        migrations.AlterField(
            model_name='match',
            name='robot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_robot2', to='Registro.robot'),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='numero_ronda',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='esta_completa',
        ),
    ]
