# Generated by Django 5.1.5 on 2025-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_match_options_alter_ronda_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ronda',
            name='lugar',
            field=models.CharField(max_length=255),
        ),
    ]
