# Generated by Django 5.1.5 on 2025-03-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_torneo_robots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['hora_programada'], 'verbose_name_plural': 'matches'},
        ),
        migrations.RenameField(
            model_name='torneo',
            old_name='robots',
            new_name='robots_inscritos',
        ),
        migrations.AddField(
            model_name='match',
            name='descripcion_resultado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ronda',
            name='categoria',
            field=models.CharField(choices=[('PROFESIONAL', 'Profesional'), ('JUNIOR', 'Junior')], default='PROFESIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ronda',
            name='esta_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pago_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='ganador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_ganados', to='Registro.robot'),
        ),
        migrations.AlterField(
            model_name='match',
            name='robot1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_robot1', to='Registro.robot'),
        ),
        migrations.AlterField(
            model_name='match',
            name='robot2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_robot2', to='Registro.robot'),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='lugar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='numero_ronda',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ronda',
            unique_together={('torneo', 'numero_ronda', 'categoria')},
        ),
    ]
